" Use <Space> as leader
let mapleader = "\<Space>"

" Fix problem with Vundle
" https://github.com/VundleVim/Vundle.vim/issues/622
" TODO: Probably not be necessary after all, will delete
" set shell=bash

" Search settings
set incsearch  " Incremental search (while typing)
set hlsearch  " Highlight search terms

" Hide search highlight by pressing Enter key
nnoremap <cr> :nohlsearch<CR>:<backspace>
nnoremap <cr> :nohlsearch<CR><CR>:<backspace><backspace>

" Initialize Vundle
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()

" Vundle plugin manager
Plugin 'VundleVim/Vundle.vim'

if (v:version >= 704)
  " AutoComplete
  Plugin 'Valloric/YouCompleteMe'

  " Snippets (not sure how much I use this)
  Plugin 'SirVer/ultisnips'
endif

" Misc
Plugin 'honza/vim-snippets'

" Airliner
Plugin 'vim-airline/vim-airline'
Plugin 'vim-airline/vim-airline-themes'

" Badwolf Theme
Plugin 'sjl/badwolf'

" Recently-opened files
Plugin 'mru.vim'

" Ack
Plugin 'mileszs/ack.vim'

" Bracket mappings (rarely use, maybe remove)
Plugin 'tpope/vim-unimpaired'

" Markers
Plugin 'kshenoy/vim-signature'

" Language or file-based syntax highlighting
Plugin 'keith/swift.vim'
Plugin 'pangloss/vim-javascript'
"Plugin 'mxw/vim-jsx'
Plugin 'chemzqm/vim-jsx-improve'
Plugin 'tweekmonster/django-plus.vim'

"let g:jsx_ext_required = 0
" Syntastic syntax  checking
"Plugin 'vim-syntastic/syntastic' "XXX: Disabling for now, glitching vim

" Python-linting
Plugin 'nvie/vim-flake8'

" Better Python styling
Plugin 'Vimjas/vim-python-pep8-indent'

" Vim markdown syntax
Plugin 'godlygeek/tabular'
Plugin 'plasticboy/vim-markdown'

" Preview markdown files - Ctrl + p
" NOTE: Requires grip (should be installed by setup script)
Plugin 'JamshedVesuna/vim-markdown-preview'

" Markdown preview settings
let vim_markdown_preview_github=1

" Fzf fuzzyfinder
Plugin 'junegunn/fzf'

" Better tab jumping
" TODO: Fork and make improvements
Plugin 'ipod825/TagJump'

" NERD Commenter
Plugin 'scrooloose/nerdcommenter'

" Vim fugitive - Git integration
Plugin 'tpope/vim-fugitive'

" Airline settings
set t_Co=256
if !exists('g:airline_symbols')
        let g:airline_symbols = {}
endif
set laststatus=2
let g:airline_theme='kolor'
set guifont=DejaVu\ Sans\ Mono\ for\ Powerline:s14
let g:airline_left_sep = ''
let g:airline_left_alt_sep = ''
let g:airline_right_sep = ''
let g:airline_right_alt_sep = ''
let g:airline_symbols.branch = ''
let g:airline_symbols.readonly = ''
let g:airline_symbols.linenr = '¶'
let g:airline_symbols.branch = '⎇'
let g:airline_symbols.paste = 'ρ'
let g:airline_symbols.whitespace = 'Ξ'

" Ultisnips settings
" Not using tab to expand
let g:UltiSnipsExpandTrigger="<tab>"
let g:UltiSnipsJumpForwardTrigger="<c-b>"
let g:UltiSnipsJumpBackwardTrigger="<c-z>"
let g:UltiSnipsEditSplit="vertical"

" Start vundle
call vundle#end()
filetype plugin indent on

" Syntax highlighting settings
syntax enable
autocmd BufRead,BufNewFile *.jinja set filetype=jinja
autocmd BufRead,BufNewFile *.html set filetype=htmldjango
autocmd BufRead,BufNewFile *.html set ts=2 sw=2 sts=2
autocmd BufRead,BufNewFile *.css set ts=2 sw=2 sts=2
autocmd BufRead,BufNewFile README set filetype=markdown
autocmd BufRead,BufNewFile Dockerfile* set filetype=dockerfile
autocmd BufRead,BufNewFile .env.* set filetype=sh

" Ctags settings
set tags=tags;/

" Fix YouCompleteMe preview window from not closing
if (v:version > 704)
  autocmd CompleteDone * pclose
endif

" Python 2 interpretter for YCM
let g:ycm_server_python_interpreter = "/usr/bin/python"

" Flake8 key mapping - <Space> + f
autocmd FileType python nnoremap <leader>f :call Flake8()<CR>

" Execute current file with python - <Space> + p + y
autocmd FileType python nnoremap <leader>py :!python %:p<CR>

" Leader mapping to insert ipdb breakpoint (use '+' to move to next line)
autocmd FileType python nnoremap <leader>pdb oimport ipdb; ipdb.set_trace()<Esc>+

" Shortcuts and fixes for typos
" Was `command`, replaced with `cnoreabbrev`
nnoremap <leader>q :q<CR>
nnoremap <leader>q! :q!<CR>
nnoremap <leader>w :w<CR>
nnoremap <leader>wq :wq<CR>
cnoreabbrev W w
cnoreabbrev Q q
cnoreabbrev Q! q!

" Better titles for tmux
autocmd BufEnter * call system("tmux rename-window " . expand("%:t:r"))
autocmd VimLeave * call system("tmux rename-window '  '")
set title

" Set Quickfix window height to be taller
let g:flake8_quickfix_height=20

" Get rid of ex mode--I never use it anyway
map Q <Nop>

"autocmd FileType qf nnoremap <buffer> <CR> <CR>:lclose<CR>

" Close QuickFix and Preview Windows
" This is easier than remembering each individual command (plus I made a
" shortcut below)
function! Close()
  lclose
  cclose
  pclose
  helpclose
endfunction

" Shortcut for Close - <Space> + c
nnoremap <leader>c :call Close()<CR>

" Vim markdown settings
let g:vim_markdown_folding_disabled = 1

" FZF settings
" https://github.com/junegunn/fzf
set rtp+=~/.fzf
let g:fzf_colors =
      \ { 'fg':      ['fg', 'Normal'],
  \ 'bg':      ['bg', 'Normal'],
  \ 'hl':      ['fg', 'Comment'],
  \ 'fg+':     ['fg', 'CursorLine', 'CursorColumn', 'Normal'],
  \ 'bg+':     ['bg', 'CursorLine', 'CursorColumn'],
  \ 'hl+':     ['fg', 'Statement'],
  \ 'info':    ['fg', 'PreProc'],
  \ 'prompt':  ['fg', 'Conditional'],
  \ 'pointer': ['fg', 'Exception'],
  \ 'marker':  ['fg', 'Keyword'],
  \ 'spinner': ['fg', 'Label'],
  \ 'header':  ['fg', 'Comment'] }

function! HashedString(string)
    let git_branch = "master"
    let hash_length = 20
    return substitute(system("echo -n " . a:string . " | md5sum | cut -c-" . hash_length), '\n\+$', '', '')
    unlet git_branch
    unlet hash_length
endfunc

" This is actually kind of useful - Use different swap directory
" for each git branch.
"
"" TODO: Use subdirectory for specific repos
"function! SetVimDir(...)
"    let verbose = "false"
"    if exists("a:1") && (a:1 == "verbose")
"        let verbose = "true"
"    endif
"    if verbose == "true"
"        echo "Verbose Mode"
"    endif

"    " It git branch, make new directory
"    " If no git branch, keep default dir
"    let parent_dir = substitute(expand("%:p:h"), '\n+\$', '', '')
"    let git_branch = substitute((system('cd ' . parent_dir . ' | git symbolic-ref --short HEAD 2>/dev/null')), '\n\+$', '', '')
"    if git_branch != ""

"        let repo_name = split(system("git remote -v | grep '(fetch)'"))[1]
"        let file_path = substitute(expand("%:p:h"), '\n\+$', '', '')

"        let git_branch_hash = HashedString(repo_name)
"        let repo_name_hash = HashedString(repo_name)
"        let file_path_hash = HashedString(file_path)

"        let dir_name = '/home/shawn/.tmp/git/' . repo_name_hash . '/' . git_branch_hash . '/' . file_path_hash

"        " Make branch directory if doesn't exit
"        if verbose
"            echo("Verifying directory " . dir_name . " exists")
"        endif
"        call system('mkdir -p ' . dir_name)
"        let &dir=dir_name
"        unlet repo_name
"        unlet dir_name
"    endif

"    unlet git_branch
"    unlet verbose
"endfunc
""call SetVimDir() - XXX: Fix this to default to user's home directory

" Tab and indentation settings
set tabstop=4
set shiftwidth=4
set softtabstop=4
set expandtab
set autoindent

" Language-specific formatting settings
autocmd FileType javascript setlocal ts=2 sw=2 sts=2

" Matching braces, etc
set showmatch

" Menu autocomplete - Show all choices
set wildmode=list:longest

" Color scheme
colorscheme badwolf
syntax on
hi Normal ctermbg=None
hi NonText ctermbg=None

" Fix key-map collision between YCM and UltiSnips
"
" TODO: Get this working
"
" let g:ycm_key_list_select_completion = ['<C-n>']
" let g:ycm_key_list_previous_completion = ['<C-p>']
" let g:UltiSnipsExpandTrigger="<tab>"
" autocmd FileType python nnoremap <leader><leader> :call UltiSnips#ExpandSnippet()<CR>
" autocmd FileType python nnoremap <leader><leader> :call UltiSnips#ExpandSnippet()<CR>
"
" Plugin 'ervandew/supertab'
"
" Supertab settings
" let g:SuperTabDefaultCompletionType = '<C-n>'
"
" Better key bindings for UltiSnipsExpandTrigger
" let g:UltiSnipsExpandTrigger="<cr>"
" let g:UltiSnipsJumpForwardTrigger="<c-j>"
" let g:UltiSnipsJumpBackwardTrigger="<c-k>"

" Syntastic settings
let g:syntastic_javascript_checkers=['eslint']

set backupdir=~/.vim/backup//
set directory=~/.vim/swap//

" Use F2 to toggle paste on/off before and after pasting
set pastetoggle=<F2>
